# Review - Nasir Hussain - 2020/05/18

In [1]:
first_name = ["Muhammad", "Nasir", "Hussain"]
last_name = ["Ali", "Husnain", "Khan"]
for fname in first_name:
    for lname in last_name:
        full_name = f"{fname} {lname}"
        print(full_name)

Muhammad Ali
Muhammad Husnain
Muhammad Khan
Nasir Ali
Nasir Husnain
Nasir Khan
Hussain Ali
Hussain Husnain
Hussain Khan


In [2]:
marks = int(input("Enter your marks : "))
print(f"Your marks are = {marks}")
grade = ""
if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
elif marks >= 60:
    grade = "C"
elif marks >= 50:
    grade = "D"
else:
    grade = "F"
print(f"Your grade is = {grade}")

Your marks are = 75
Your grade is = B


In [3]:
age = int(input("Enter your age : "))
print(f"Age = {age}")
if age >20:
    print("You are good to go as you are above 20 years of age")
    gender = input("Enter your gender ( male / female ) : ")
    print(f"Gender = {gender}")
    if gender == "male":
        print("You are good to go as you are male")
        job_status = input("Enter your job status ( employed / un-employed ) : ")
        print(f"Job Status = {job_status}")
        if job_status == "un-employed":    
            print("You got 50% discount on fee")
        else:
            print("Sorry this discount is only for un-employed")
            print("No discount for you")   
    else:
        print("Sorry this discount is only for males")
        print("No discount for you")
else:
    print("Sorry you are less than 20 years old")
    print("No discount for you")

Age = 29
You are good to go as you are above 20 years of age
Gender = male
You are good to go as you are male
Job Status = employed
Sorry this discount is only for un-employed
No discount for you


In [4]:
name = "Hassan Ali Khan"
for letter in name:
    print(letter)

H
a
s
s
a
n
 
A
l
i
 
K
h
a
n


In [5]:
names= ["Hassan", "Ali", "Khan"]
for name in names:
    print(name)

Hassan
Ali
Khan


---

In [6]:
# Class
# Object
# Constructor

In [7]:
class Student():
    # property / characteristic >>> Variable
    def __init__(self,name,age,course,fee):
        self.name = name
        self.age = age
        self.course = course
        self.fee= fee
    # behaviour >>> function / method
    def attendingClass(self):
        print(f"{self.name} is of {self.age} attending class of {self.course} and fee is {self.fee}.")
    # submittingFee
    # appearingExam


In [8]:
st1 = Student("Hassan",29,"AI",1500)
print(st1.name)
print(st1.age)
print(st1.course)
print(st1.fee)

Hassan
29
AI
1500


In [9]:
st1.attendingClass()

Hassan is of 29 attending class of AI and fee is 1500.


---

In [10]:
a = range(10)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [11]:
def myFunction():
    print("My name is Hassan Ali Khan")
    print("I am function not returning anything")
    return 100+100
    print("After return")
value = myFunction()
value

My name is Hassan Ali Khan
I am function not returning anything


200

---

In [12]:
dic1 = {"name":["w","e","r","t"]}
dic2 = {"nums":[1,2,3,4]}
mydic = {"myd1":dic1,"myd2":dic2}
print(mydic)
print(mydic["myd1"])
print(mydic["myd2"])
print(mydic["myd2"]["nums"])
print(mydic["myd2"]["nums"][2])

{'myd1': {'name': ['w', 'e', 'r', 't']}, 'myd2': {'nums': [1, 2, 3, 4]}}
{'name': ['w', 'e', 'r', 't']}
{'nums': [1, 2, 3, 4]}
[1, 2, 3, 4]
3


In [13]:
d2List = [[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]]
print(d2List)
print(d2List[2][1])

[[1, 2, 3], [11, 22, 33], [111, 222, 333], [1111, 2222, 3333]]
222


In [14]:
import numpy as np
q = np.arange(20).reshape(4,5)
print(q)
print(q[2,2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
12


In [15]:
b = []
for i in range(10):
    b.append(i)
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]